client/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView

app_name = "client"
urlpatterns = [
    path("", views.ClientsListView, name="clients"),
    path("clientDetail/<int:pk>", views.ClientsDetailView, name="detail"),
    path("createClient/", views.ClientCreateView, name="createClient"),
    path("createPermanent/", views.PermanentCreateView, name='createPermanent'),
    path(
        "clientCancellatioin/<int:pk>",
        views.ClientCancellation,
        name="clientCancellation",
    ),
    
    path("updatePermanent/<int:pk>", views.UpdateNonPermenent, name='updatePermanent'),
    path("updateNonPermanent/<int:pk>", views.UpdateNonPermenent, name='updateNonPermanent'),
    
    # pdf 
    path("clientsPdf/", views.clientPdfGenerator, name="clientsPdf"),
    
    # Pos url
    path("pos/", views.Pos, name="pos"),
    path('posData/', views.posData, name='posData'),
]

dashboard/urls.py
from django.urls import path
from dashboard.views import Dashboard

app_name = "dashboard"
urlpatterns = [path("", Dashboard, name="dashboard")]

expenses/urls.py
from expenses.views import Expenses, ExpenseCancellation, dailyReport, monthlyReport, customReport
from django.urls import path

app_name = 'expenses'
urlpatterns = [
    path('', Expenses, name='expenses' ),
    path('dailyReport/', dailyReport,  name='dailyReport'),
    path('customReport/', customReport,  name='customReport'),
    path('monthlyReport/', monthlyReport,  name='monthlyReport'),
    path('cancelExpense/<int:pk>', ExpenseCancellation, name='cancelExpense'),
]

linspot_business_management_system/users/urls.py
from django.urls import path

from linspot_business_management_system.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'
urlpatterns = [
    path("create/", views.TransactioinCreateView, name="create"),
    path('account/<int:pk>', views.Account, name='account'),
    path('pdf/<int:pk>', views.clientAccountPdfGenerator, name='clientAccount'),
    path('transactions/', views.transactions, name='transactions'),
    path('dailyReport/', views.dailyReport,  name='dailyReport'),
    # path('customReport/', views.customReport,  name='customReport'),
    path('monthlyReport/', views.monthlyReport,  name='monthlyReport'),
]

vouchers/urls.py
from . import views
from django.urls import path

app_name = 'vouchers'

urlpatterns = [
    path('addCategory/', views.addCategory, name='addCategory'),
    path("voucherList/", views.vouchersList,  name="voucherList"),
    path("voucherFiles/", views.voucherFiles,  name="voucherFiles"),
    path("populateVouchers/<int:pk>", views.populateVouchers,  name="populateVouchers"),
]

client/models.py
from django.db import models

# from phonenumber_field.modelfields import PhoneNumberField

member_status = (("non permanent", "non permanent"), ("permanent", "Permanent"))
station_status = (('occupied', 'occupied'), ('vaccant', 'vaccant'))

class WorkStation(models.Model):
    station = models.CharField(max_length=4)
    type = models.CharField(max_length=10)
    status = models.CharField(max_length=50, choices=station_status)

    def __str__(self) -> str:
        return f'{self.station} ({self.status})'
    
class Client(models.Model):
    name = models.CharField(max_length=50)
    phonenumber = models.CharField(max_length=50)
    address = models.CharField(max_length=50, null=True, blank=True)
    id_number = models.CharField(max_length=50, null=True, blank=True)
    station_number = models.OneToOneField(WorkStation, on_delete=models.CASCADE, null=True, blank=True)
    member_status = models.CharField(choices=member_status, max_length=50)
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)
    count = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        return self.name


class Cancellation(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)
    note = models.TextField()

    def __str__(self):
        return self.client.name


class Account(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    transaction = models.ForeignKey(
        "transactions.Transaction", on_delete=models.CASCADE
    )
    status = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.client.name} ({self.status})"


    

dashboard/models.py
from django.db import models

# Create your models here.

linspot_business_management_system/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Linspot business management system.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

linspot_business_management_system/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


@login_required(login_url="/accounts/login")
def Dashboard(request):
    return render(request, "dashboard.html")

linspot_business_management_system/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

linspot_business_management_system/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock title %}
{% block content %}
  <h1>Forbidden (403)</h1>
  <p>
    {% if exception %}
      {{ exception }}
    {% else %}
      You're not allowed to access this page.
    {% endif %}
  </p>
{% endblock content %}

linspot_business_management_system/templates/base.html
{% load static i18n %}<!DOCTYPE html>
{% get_current_language as LANGUAGE_CODE %}
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="x-ua-compatible" content="ie=edge" />
    <title>
      {% block title %}
        Linspot business management system
      {% endblock title %}
  </title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="description"
        content="A software which manages the day to day business activities of Linkspot thus sales for day desks, internet cafe, monthly subscriptions, expenses, reporting and asset registry" />
  <meta name="author"
        content="casy moyo" />
  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}" />
  {% block css %}
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
          integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer" />
<!-- Your stuff: Third-party CSS libraries go here -->
<link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>

<!-- This file stores project-specific CSS -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" integrity="sha512-nMNlpuaDPrqlEls3IX/Q56H36qvBASwb3ipuo3MxeWbsQB1881ox0cRv7UPTgBlriqoynt35KjEwgGUeUXIPnw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<link href="{% static 'css/project.css' %}" rel="stylesheet" />


{% endblock css %}
<!-- Le javascript
    ================================================== -->
{# Placed at the top of the document so pages load faster with defer #}
{% block javascript %}


<!-- Bootstrap JS -->
<script defer
        src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
        integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
        crossorigin="anonymous"
        referrerpolicy="no-referrer"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.5.1/chosen.min.css">

        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/chosen/1.5.1/chosen.jquery.min.js"></script>
     <script defer src="{% static 'js/project.js' %}"></script>

     <script defer src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js" integrity="sha512-2ImtlRlf2VVmiGZsjm9bEyhjGW4dU7B6TNwh/hx/iSByxNENtj3WVE6o/9Lj4TJeVXPi4bnOIMXFIJJAeufa0A==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
{% endblock javascript %}
</head>
<body>
  <div class="mb-1">
    {% include "components/navbar.html" %}
  </div>
  <div class="row main-app">
    <div class="col-2 justify-content-between">
      <div class="aside d-flex flex-column shadow">
        <ul class="aside-links list-unstyled px-2 mt-3">
          <li>
            <a href="{% url 'dashboard:dashboard' %}">
              <i class='bx bxs-dashboard px-2'></i>
              Dashboard
            </a>
          </li>
          <li>
            <a href="{% url 'client:pos' %}">
              <i class='bx bx-shape-square px-2'></i>
              Point Of Sale
            </a>
          </li>
          <li>
            <a href="{% url 'client:clients' %}">
              <i class='bx bx-group px-2'></i>
              Clients
            </a>
          </li>
          <li>
            <a href="{% url 'transactions:transactions' %}">
              <i class='bx bx-money-withdraw px-2'></i>
              Sales
            </a>
          </li>
          <li>
            <a href="{% url 'expenses:expenses'%}">
              <i class='bx bx-credit-card-front px-2'></i>
              Expenses
            </a>
          </li>
          <li>
            <a href="{% url 'vouchers:voucherFiles'%}">
              <i class='bx bx-file'></i>
              Vouchers
            </a>
          </li>
          <li>
            <a href="">
              <i class='bx bxs-report' ></i>
              Reports
            </a>
          </li>
          <li>
            <a href="">
              <i class='bx bx-user px-2'></i>
              Users
            </a>
          </li>
        </ul>
      </div>
      <small>Developed by
        <span>Casy</span>
      </small>
    </div>

    <div class="col-10">
      <div class='main-app container'>
        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-dismissible {% if message.tags %}alert-{{ message.tags }}{% endif %}">
              {{ message }}
              <button type="button"
                      class="btn-close"
                      data-bs-dismiss="alert"
                      aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
        {% block content %}

        {% endblock content %}
      </div>
    </div>
  </div>

  {% block modal %}
  {% endblock modal %}
  {% block inline_javascript %}
    {% comment %}
    Script tags with only code, no src (defer by default). To run
    with a "defer" so that you run inline code:
    <script>
      window.addEventListener('DOMContentLoaded', () => {
        /* Run whatever you want */
      });
    </script>
    {% endcomment %}
  {% endblock inline_javascript %}
</body>
</html>

linspot_business_management_system/templates/dashboard.html
{% extends "base.html" %}
{% load static %}
{% block title %}Dashboard{% endblock title %}
{% block content %}
<div class="dashboard mt-3">
    <div class="title d-flex justify-content-between align-items-center">
        <h4>Dashboard</h4>
        <span class="py-2 shadow px-2">Income $2000</span>
    </div>
    <div class="row mt-3">
        <div class="col-4">
            <div class="card shadow">
                <div class="card-body">
                    <h5 class="d-flex justify-content-between"> 
                        <span>Members</span>
                        <span class="number">100</span>
                    </h5>
                    <ul class="list-unstyled">
                        <li class="d-flex justify-content-between">
                            <a href="">Permanent</a>
                            <span class="number">100</span>
                        </li>
                        <li class="d-flex justify-content-between">
                            <a href="">Non Permanent</a>
                            <span class="number">100</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        
        <!-- sales -->
        <div class="col-4">
            <div class="card shadow">
                <div class="card-body">
                    <h5 class="d-flex justify-content-between"> 
                        <span>Sales</span>
                        <span class="number">100</span>
                    </h5>
                    <ul class="list-unstyled">
                        <li class="d-flex justify-content-between">
                            <a href="">Day Desks</a>
                            <span class="number">100</span>
                        </li>
                        <li class="d-flex justify-content-between">
                            <a href="">Internet Cafe</a>
                            <span class="number">100</span>
                        </li>
                        <li class="d-flex justify-content-between">
                            <a href="">Rental Income</a>
                            <span class="number">100</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- expenses -->
        <div class="col-4">
            <div class="card shadow">
                <div class="card-body">
                    <h5 class="d-flex justify-content-between"> 
                        <span>Expenses</span>
                        <span class="number">100</span>
                    </h5>
                    <ul class="list-unstyled">
                        <li class="d-flex justify-content-between">
                            <a href="">Total</a>
                            <span class="number">100</span>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

linspot_business_management_system/templates/pos.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}POS{% endblock title %}
{% block content %}
<div class="pos">
    <!-- //loading spinner -->
    <div class="spinner">
        <div class="d-flex flex-column justify-content-center align-items-center spinner-content">
            {% include "components/spinnerComponent.html" %}
        </div>
    </div>
    <div>
        <div class="title d-flex justify-content-end align-items-center" style="opacity: 1 !important;">
            <h5 class="w-100">Point Of Sale</h5>
            <div class="d-flex align-items-center justify-content-end w-100">
                <span class="py-2 shadow px-2">
                    <button class="btn btn-primary btn-sm client-add" type="button">
                        <i class='bx bx-user-plus px-2'></i>Non Permanent</i>
                    </button>
                </span>
                <span class="py-2 shadow px-2">
                    <button class="btn btn-secondary btn-sm permanent" type="button">
                        <i class='bx bx-user-plus px-2'></i> Permanent</i>
                    </button>
                </span>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-9">
                <div class="cafe">
                    <h6>Internet Cafe</h6>
                    <table class='todays-vouchers list-unstyled p-2 table table-dark table-striped mt-4 table-responsive'>
                        {% for voucher in vouchers %}
                        <tr>
                            <td>{{voucher.client}} ({{voucher.work_station.station}})</td>
                            <td class='px-2'>{{voucher.start_time}}</td>
                            <td class='px-3'><i class='bx bx-chevron-right bx-m'></i></td>
                            <td class='px-2'>{{voucher.end_time}}</td>
                            <td><button class='btn btn-primary bg-primary btn-sm' data-id = {{voucher.id}}>done</button></td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
                <div class="Day-Desks mt-3">
                    <h6>Day Desks</h6>
                    <table class='todays-vouchers list-unstyled p-2 table-primary table table-striped mt-4 table-responsive'>
                        {% for day in desks %}
                        <tr>
                            <td>{{day.client}} ({{day.work_station.station}})</td>
                        </tr>
                        {% endfor %}
                    </table>
                </div>
            </div>
            <div class="col-3 border p-3">
                <form action="" method="post" id="pos_form">
                    {% csrf_token %}
                    {{form|crispy}}
                    <button class="btn btn-secondary w-100 pos-btn" type="button">Charge</button>
                </form>
            </div>
        </div>
    </div>

    <section class="cafe-modal hidden">{% include "clients/pos/voucher_list.html" %}</section>

    <section class="permanent-modal hidden">{% include "clients/pos/addPermanent.html" %}</section>

    <section class="client-modal hidden">{% include "clients/pos/addClientComponent.html" %}</section>

    <div class="overlay hidden"></div>
</div>

<script src="{% static 'js/jquery.js' %}"></script>
<script>

    $(document).ready(function() {
        $('#id_client').select2(
            {placeholder: 'Select Client'}
        );
        $('#id_product').select2(
            {placeholder: 'Select Product'}
        );
        $('#id_work_station').select2(
            {placeholder: 'Select Workstation'}
        );
    });

    document.addEventListener('DOMContentLoaded', (event) => {
        //pos
        const cafe = document.querySelector('.internet')
        const day = document.querySelector('.day')
        const m_rentals = document.querySelector('.m-r')
        const resource = document.querySelector('.resource')
        const addVoucher = document.querySelectorAll('.add')
        const voucher = document.querySelector('.voucher')
        const posDetails = document.querySelector('.posDetails')
        const pMenu = document.querySelector('.p-menu')
        const ordinary = document.querySelector('.ordinary')
        const laptop = document.querySelector('.laptop')
        const monthlRent = document.querySelector('.m-r')
        const client_obj =document.querySelectorAll('.op_value')



        //modal
        const modal = document.querySelector(".cafe-modal");
        const clientModal = document.querySelector('.client-modal')
        const overlay = document.querySelector(".overlay");
        const clientAddBtn = document.querySelector('.client-add')
        const openModalBtn = document.querySelector(".btn-open");
        const closeModalBtn = document.querySelectorAll(".close")
        const spinner = document.querySelector('.spinner')
        const permanent = document.querySelector('.permanent')
        const permanentModal = document.querySelector('.permanent-modal')

        let voucher_number = ''

        //spin loader
        function spin(){
            spinner.classList.add('hidden')
            console.log(spinner)
        }
        setTimeout(spin, 3000)

        //function to effect pos menu
        function hide(){
            posDetails.classList.remove('hidden')
            pMenu.classList.add('hidden')
        }

        //add client modal
        clientAddBtn.addEventListener(
            'click', ()=>{
                clientModal.classList.remove("hidden");
                overlay.classList.remove("hidden");
            }
        )

        //permanent modal
        permanent.addEventListener(
            'click' , ()=>{
                console.log('click')
                permanentModal.classList.remove("hidden");
                overlay.classList.remove("hidden");
            }
        )


        //monthly rent
        //monthlRent.addEventListener(
        //    'click', ()=>{
        //        document.querySelector('.monthly').classList.remove('hidden')
        //        hide()
        //}
        //)


        //close modal
        closeModalBtn.forEach((btn)=>{
            btn.addEventListener(
                'click', ()=>{
                    modal.classList.add("hidden");
                    overlay.classList.add("hidden");
                    clientModal.classList.add('hidden')
                    resource.value = ''
                }
            )
        })

        //post client data
        $('#client_form').submit(function(e) {
            e.preventDefault();
            const url = "/clients/createClient/"
            const data = {
              name : $('#client_name').val(),
              phonenumber : $('#client_phonenumber').val(),
              csrfmiddlewaretoken: $("[name=csrfmiddlewaretoken]").val()
            }

            $.ajax({
              url: url,
              type: 'POST',
              data: data,
            }).done(function(response) {
                console.log(response)
                if(response.success){
                    clientData()
                    clientModal.classList.add('hidden')
                    overlay.classList.add("hidden");
                    console.log('loaded')
                }
              })
            $(this).trigger('reset')
        })

        //permanent client
        $('#permanent_form').submit(function(e) {
            e.preventDefault();
            const url = "/clients/createPermanent/"
            const data = {
              name : $('#permanent_name').val(),
              phonenumber : $('#permanent_phonenumber').val(),
              address: $('#permanent_address').val(),
              station: $('#permanent_station').val(),
              id_number: $('#permanent_id_number').val(),
              csrfmiddlewaretoken: $("[name=csrfmiddlewaretoken]").val()
            }

            $.ajax({
              url: url,
              type: 'POST',
              data: data,
            }).done(function(response) {
                if(response.success){
                    clientData()
                    permanentModal.classList.add('hidden')
                    overlay.classList.add("hidden");
                    console.log('loaded')
                }else{
                    console.log(response['warning'])
                }
              })
            $(this).trigger('reset')
          })

        document.querySelector('.pos-btn').addEventListener(
            'click', ()=>{
            console.log('clicked')
            const url = "/transactions/create/"
            const data = {
              client : $('#id_client').val(),
              amount : $('#id_amount_0').val(),
              product : $('#id_product').val(),
              voucher : voucher,
              station : $('#id_work_station').val(),
              csrfmiddlewaretoken: $("[name=csrfmiddlewaretoken]").val()
            }
            console.log(data)
            $.ajax({
              url: url,
              type: 'POST',
              data: data,
            }).done(function(response) {
                if(response.success){
                    console.log(response)
                }else{
                    console.log(response['warning'])
                }
              })
            $(this).trigger('reset')
          })
        })
</script>
{% endblock content %}