client/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView

app_name = "client"
urlpatterns = [
    path("", views.ClientsListView, name="clients"),
    path("clientDetail/<int:pk>", views.ClientsDetailView, name="detail"),
    path("createClient/", views.ClientCreateView, name="createClient"),
    path("createPermanent/", views.PermanentCreateView, name='createPermanent'),
    path(
        "clientCancellatioin/<int:pk>",
        views.ClientCancellation,
        name="clientCancellation",
    ),
    
    path("updatePermanent/<int:pk>", views.UpdateNonPermenent, name='updatePermanent'),
    path("updateNonPermanent/<int:pk>", views.UpdateNonPermenent, name='updateNonPermanent'),
    
    # pdf 
    path("clientsPdf/", views.clientPdfGenerator, name="clientsPdf"),
    
    # Pos url
    path("pos/", views.Pos, name="pos"),
    path('posData/', views.posData, name='posData'),
]

expenses/urls.py
from expenses.views import Expenses, ExpenseCancellation, dailyReport, monthlyReport, customReport
from django.urls import path

app_name = 'expenses'
urlpatterns = [
    path('', Expenses, name='expenses' ),
    path('dailyReport/', dailyReport,  name='dailyReport'),
    path('customReport/', customReport,  name='customReport'),
    path('monthlyReport/', monthlyReport,  name='monthlyReport'),
    path('cancelExpense/<int:pk>', ExpenseCancellation, name='cancelExpense'),
]

linspot_business_management_system/users/urls.py
from django.urls import path

from linspot_business_management_system.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

expenses/models.py
from django.db import models
from djmoney.models.fields import MoneyField

class Expense(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=255, blank=True)
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)
    amount = MoneyField(max_digits=14, decimal_places=2, default_currency="USD")
    date_created = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.name} ({self.amount})'
    
class ExpenseCancellation(models.Model):
    expense = models.OneToOneField(Expense, on_delete=models.CASCADE)
    reason = models.CharField(max_length=255, blank=True)
    date_created = models.DateField(auto_now_add=True)
    
    def __str__(self):
        return f'{self.reason} ({self.expense})'
    
    
    

linspot_business_management_system/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Linspot business management system.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

expenses/forms.py
from expenses.models import Expense
from django.forms import ModelForm

class ExpensesForm(ModelForm):
    class Meta:
        model = Expense
        exclude = ("user",)

linspot_business_management_system/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

expenses/views.py
import datetime
from datetime import timezone
from django.db.models import Q, Sum
from django.contrib import messages
from expenses.forms import ExpensesForm
from expenses.models import Expense, ExpenseCancellation
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_list_or_404

# pdf
from config.utils import render_to_pdf


@login_required(login_url="/accounts/login")
def Expenses(request):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    expenses = Expense.objects.filter(
        Q(date_created__icontains=q) |
        Q(name__icontains=q) |
        Q(amount__icontains=q) |
        Q(user__name__icontains=q)
    )
    # processing expense creation
    form = ExpensesForm()
    if request.method == 'POST':
        form = ExpensesForm(request.POST)
        if form.is_valid():
            exp_obj = form.save(commit=False)
            exp_obj.user = request.user
            exp_obj.save()
            messages.success(request, 'Expense successfully created')
            return redirect('expenses:expenses')
        messages.warning(request, 'Failed to create expense')
    return render(request, 'expenses/expenses.html', {
        'expenses': expenses or Expense.objects.all(),
        'form': form
    })


@login_required(login_url="/accounts/login")
def ExpenseCancellation(request, pk):
    exp = get_list_or_404(Expense, id=pk)
    if request.method == 'POST':
        exp_obj = ExpenseCancellation(
            user=request.user,
            expense=exp,
            reason=request.POST['reason']
        )
        exp_obj.save()
        messages.success(request, 'Expense successfully cancelled')
        return redirect('expenses:expenses')
    messages.warning(request, 'cancellation failed')
    return redirect('expenses:expenses')


# function for total amount of expenses computation
# worried with performance as the dataset increases :(
def expensesTotal(expenses_data):
    total_expenses = 0
    exp = expenses_data.annotate(total=Sum('amount'))
    for exp in exp:
        total_expenses = exp.amount + total_expenses
    return total_expenses


# daily report
@login_required(login_url="/accounts/login")
def dailyReport(request):
    template_name = 'reports/expensesPdf.html'
    # query today's expenses data
    expenses = Expense.objects.filter(date_created=datetime.date.today())
    return render_to_pdf(
        template_name,
        {
            "expenses": expenses,
            'title': 'Today(s) Expenses',
            'date': datetime.date.today(),
            'total': expensesTotal(expenses)
        },
    )


# monthly report
@login_required(login_url="/accounts/login")
def monthlyReport(request):
    # computation for this month data
    today = datetime.date.today()
    current_month = today.month

    template_name = 'reports/expensesPdf.html'
    expenses = Expense.objects.filter(date_created__month=current_month)
    return render_to_pdf(
        template_name,
        {
            "expenses": expenses,
            'title': 'Monthly Expenses',
            'date': datetime.date.today(),
            'total': expensesTotal(expenses)
        },
    )


@login_required(login_url="/accounts/login")
def customReport(request):
    end_date = request.GET['date_from']
    start_date = request.GET['date_to']
    print(end_date, start_date)
    template_name = 'reports/expensesPdf.html'

    expenses = Expense.objects.filter(date_created__gte=start_date, date_created__lte=end_date)
    print(expenses)
    return render_to_pdf(
        template_name,
        {
            "expenses": expenses,
            'title': 'Today(s) Expenses',
            'date': datetime.date.today(),
            # 'total': custom_total_amount['amount__sum']
        },
    )

linspot_business_management_system/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

linspot_business_management_system/templates/expenses/addExpense.html
{% load crispy_forms_tags %}
{% block content %}
<div class="client-add-form" class="d-flex justify-content-center align-items-center">
    <div class="menu-buttons d-flex justify-content-between align-items-center">
        <div>
            <h5>Add Expense</h5>
        </div>
        <div class="px-3">
            <span>
                <button class="btn btn-danger close">cancel</button>
            </span>
        </div>
    </div>
    <div class="container d-flex justify-content-center mt-4 border p-5" >
        <form method="post" id="client_form" class="w-50">
            {% csrf_token %}
            {{form|crispy }}
            <button class="primaryAction btn btn-primary w-100" type="submit">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

linspot_business_management_system/templates/expenses/expenses.html
{% extends "base.html" %}
{% load static %}
{% block title %}Expenses{% endblock title %}
{% block content %}
<div class="dashboard mt-3">
    <div class="row">
        <div class="title d-flex justify-content-between align-items-center" style="opacity: 1 !important;">
          <h4>
            <span class="px-1">
                <i class='bx bxs-circle'></i>
                Expenses Transactions
            </span>
          </h4>
            <div class="d-flex align-items-center">
                <span class="py-2 shadow px-2">
                    <button class="btn btn-secondary expenses">add expenses</button>
                </span>
                <span class="py-2 shadow px-2">
                    <form method="get" class="d-flex align-items-center">
                        <input type="search" name="q" class="form-control shadow" placeholder="Search expense">
                    </form>
                </span>
            </div>
        </div>
        <div class="col-10">
            <div class="row mt-3">
                <table class="table table-responsive table-striped">
                    <thead>
                        <th>Date</th>
                        <th>Name</th>
                        <th>Details</th>
                        <th>Amount</th>
                        <!-- <th>Actions</th> -->
                    </thead>
                    <tbody>
                        {% for expense in expenses %}
                            <tr>
                                <td>{{expense.date_created}}</td>
                                <td>{{expense.name}}</td>
                                <td>{{expense.description}}</td>
                                <td>{{expense.amount}}</td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-2">
            <div class="container mt-5">
                <div class="report-btns">
                    <div class="mt-2 mb-2">
                        <a href="{% url 'expenses:dailyReport' %}" class="btn btn-primary text-light w-100">Daily report</a>
                    </div>
                    <div class="mt-2">
                        <a href="{% url 'expenses:monthlyReport' %}" class="btn btn-primary text-light w-100">Monthly report</a>
                    </div>
                    <div class="mt-2 mb-2">
                        <button class="btn btn-primary text-light w-100 custom">Custom report</button>
                    </div>
                </div>
                <div class="custom-form mt-2 hidden">
                    <div class="back w-100 py-2 px-2">
                        <i class='bx bxs-left-arrow' style="color: #F99417;"></i>
                        <small>back</small>
                        <hr style="border: 1px solid #333 !important;">
                    </div>
                    <p class="mt-3">Choose dates</p>
                    <form method="get" id='custom_form'>

                        <input type="text" name="q" value="custom" hidden>
                        <div>
                            <label for="id_from">From</label>
                            <input type="date" name="from" id="id_from" class="form-control">
                        </div>
                        <div>
                            <label for="id_from">To</label>
                            <input type="date" name="to" id="id_to" class="form-control">
                        </div>
                        <div class="d-flex justify-content-end mt-3">
                            <button class="btn btn-secondary" type="submit" >submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    <section class="expenses-modal hidden">{% include "expenses/addExpense.html" %}</section>
    <div class="overlay hidden"></div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        const expenses = document.querySelector('.expenses');
        const overlay = document.querySelector(".overlay");
        const expensesModal = document.querySelector('.expenses-modal');
        const closeModalBtn = document.querySelectorAll(".close");

        //custom report
        const reportBtn = document.querySelector('.custom');
        const backBtn = document.querySelector('.back');


        expenses.addEventListener(
            'click', ()=>{
                expensesModal.classList.remove("hidden");
                overlay.classList.remove("hidden");
            }
        )

        closeModalBtn.forEach((btn)=>{
            btn.addEventListener(
                'click', ()=>{
                    expensesModal.classList.add("hidden");
                    overlay.classList.add("hidden");
                }
            )
        })

        reportBtn.addEventListener(
            'click', ()=>{
                document.querySelector('.custom-form').classList.remove('hidden');
                document.querySelector('.report-btns').classList.add('hidden');
            }
        )

        backBtn.addEventListener(
            'click', ()=>{
                document.querySelector('.custom-form').classList.add('hidden');
                document.querySelector('.report-btns').classList.remove('hidden');
            }
        )

        $('#custom_form').submit(function(e) {
            e.preventDefault();
            const data = {
                date_from: $('#id_from').val(),
                date_to: $('#id_to').val(),
            }
            console.log(data)
            $.ajax({
                url: '{% url 'expenses:customReport'%}',
                type: 'GET',
                data: data,
                }).done(function(response) {

            })
        })

    })
</script>
{% endblock content %}