client/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView

app_name = "client"
urlpatterns = [
    path("", views.ClientsListView, name="clients"),
    path("clientDetail/<int:pk>", views.ClientsDetailView, name="detail"),
    path("createClient/", views.ClientCreateView, name="createClient"),
    path("createPermanent/", views.PermanentCreateView, name='createPermanent'),
    path(
        "clientCancellatioin/<int:pk>",
        views.ClientCancellation,
        name="clientCancellation",
    ),
    
    path("updatePermanent/<int:pk>", views.UpdateNonPermenent, name='updatePermanent'),
    path("updateNonPermanent/<int:pk>", views.UpdateNonPermenent, name='updateNonPermanent'),
    
    # pdf 
    path("clientsPdf/", views.clientPdfGenerator, name="clientsPdf"),
    
    # Pos url
    path("pos/", views.Pos, name="pos"),
    path('posData/', views.posData, name='posData'),
]

expenses/urls.py
from expenses.views import Expenses, ExpenseCancellation, dailyReport, monthlyReport, customReport
from django.urls import path

app_name = 'expenses'
urlpatterns = [
    path('', Expenses, name='expenses' ),
    path('dailyReport/', dailyReport,  name='dailyReport'),
    path('customReport/', customReport,  name='customReport'),
    path('monthlyReport/', monthlyReport,  name='monthlyReport'),
    path('cancelExpense/<int:pk>', ExpenseCancellation, name='cancelExpense'),
]

linspot_business_management_system/users/urls.py
from django.urls import path

from linspot_business_management_system.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'
urlpatterns = [
    path("create/", views.TransactioinCreateView, name="create"),
    path('account/<int:pk>', views.Account, name='account'),
    path('pdf/<int:pk>', views.clientAccountPdfGenerator, name='clientAccount'),
    path('transactions/', views.transactions, name='transactions'),
    path('dailyReport/', views.dailyReport,  name='dailyReport'),
    # path('customReport/', views.customReport,  name='customReport'),
    path('monthlyReport/', views.monthlyReport,  name='monthlyReport'),
]

linspot_business_management_system/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Linspot business management system.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

transactions/models.py
from django.db import models
from djmoney.models.fields import MoneyField


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = MoneyField(max_digits=14, decimal_places=2, default_currency="USD")

    def __str__(self):
        return self.name


class Transaction(models.Model):
    client = models.ForeignKey("client.Client", on_delete=models.CASCADE)
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)
    amount = MoneyField(max_digits=14, decimal_places=2, default_currency="USD")
    owing = MoneyField(
        max_digits=14, decimal_places=2, default_currency="USD", default=0,
        blank = True
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE, blank=True, null=True)
    work_station = models.ForeignKey("client.WorkStation", on_delete=models.CASCADE, blank=True, null=True)
    # note = models.TextField(blank=True) 
    date_created = models.DateField(auto_now_add=True)
    date_updated = models.DateField(auto_now=True)
    date_due = models.DateField(blank=True, null=True)
    status = models.CharField(max_length=10, default='')

    class Meta:
        ordering = ["-date_created"]

    def __str__(self):
        return f"{self.client.name} ({self.product.name})"


class TransactionLog(models.Model):
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)
    action = models.CharField(max_length=50)
    date_created = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ["-date_created"]

    def __str__(self):
        return f"{self.date_created} ({self.user.username})"

linspot_business_management_system/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

transactions/forms.py
from client.models import Client
from transactions.models import Transaction
from django import forms


class TransactionForm(forms.ModelForm):
    
    class Meta:
        model = Transaction
        exclude = ("user", 'owing', 'date_due', 'status')
      

linspot_business_management_system/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

transactions/views.py
from datetime import date
import moneyed
from . import forms, models
from django.db.models import Q, Sum
from django.contrib import messages
from django.http import JsonResponse
from config.utils import render_to_pdf
from datetime import datetime, timedelta
from client.models import Client, WorkStation
from vouchers.models import vouchers, voucherTransaction
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_list_or_404, get_object_or_404


@login_required(login_url="/accounts/login")
def transactions(request):

    trans = request.GET.get('q') if request.GET.get('q') is not None else models.Transaction.objects.filter(
        date_created=date.today())
    total_amount = trans.aggregate(Sum('amount'))
    return render(
        request,
        'transactions/transactions.html',
        {
            'transactions': trans,
            'total': total_amount['amount__sum']
        }
    )


@login_required(login_url="/accounts/login")
def TransactioinCreateView(request):
    if request.method == 'POST':
        # get client object and product object
        cl = Client.objects.get(id=request.POST['client'])
        p = models.Product.objects.get(id=request.POST['product'])
        print(p)
        # validate amount
        if int(request.POST['amount']) < 0 or int(request.POST['amount']) == 0:
            return JsonResponse({'warning': 'amount cant be zero or below zero'})
        if str(p) in ['cafe(1)', 'cafe(2)', 'cafe(3)', 'cafe(4)', 'cafe(5)']:
            # product and voucher matching (conditional over cafe products)
            if str(p) == 'cafe(1)':
                vou = vouchers.objects.filter(file__category=1)
                voucher = vou.filter(status='unused').first()
                e_time = datetime.now() + timedelta(minutes=65)  # 1 hour and 5 minutes for preparation
            elif str(p) == 'cafe(2)':
                vou = vouchers.objects.filter(file__category=2)
                voucher = vou.filter(status='unused').first()
                e_time = datetime.now() + timedelta(minutes=125)  # 2 hours and 5 minutes for preparation
            elif str(p) == 'cafe(3)':
                vou = vouchers.objects.filter(file__category=3)
                voucher = vou.filter(status='unused').first()
                e_time = datetime.now() + timedelta(minutes=185)  # 3 hours and 5 minutes for preparation
            elif str(p) == 'cafe(4)':
                vou = vouchers.objects.filter(file__category=4)
                voucher = vou.filter(status='unused').first()
                e_time = datetime.now() + timedelta(minutes=245)  # 4 hours and 5 minutes for preparation
            elif str(p) == 'cafe(5)':
                vou = vouchers.objects.filter(file__category=5)
                voucher = vou.filter(status='unused').first()
                e_time = datetime.now() + timedelta(minutes=300)  # 5 hours and 5 minutes for preparation
            else:
                return JsonResponse({'voucher_message': 'Product doesnt exists'})

                # update the voucher status
            vou_obj = vouchers.objects.get(id=voucher.id)
            vou_obj.status = 'used'

            # create a voucher transaction
            vou_transaction_obj = voucherTransaction(
                vouch=vou_obj,
                client=cl,
                user=request.user,
                start_time=datetime.now(),
                end_time=e_time,
                work_station=WorkStation.objects.get(id=request.POST['station'])
            )

            # create transaction
            day_obj = models.Transaction(
                user=request.user,
                client=cl,
                status='cafe',
                product=p,
                amount=request.POST['amount'],
                work_station=WorkStation.objects.get(id=request.POST['station'])
            )
            day_obj.save()
            vou_obj.save()
            vou_transaction_obj.save()

            # client sale count (if exist)

            if models.Transaction.objects.filter(id=cl.id).exists():
                cl.count += 1
                cl.save()
            else:
                cl.count = 1
                cl.save()
            return JsonResponse({
                'success': 'transaction successfully created'
            })
        elif str(p) in ['premium', 'professional', 'standard']:
            # calculate amount owing
            c = p.price

            if moneyed.Money(request.POST['amount'], 'USD') < p.price:
                owing_amount = p.price - moneyed.Money(request.POST['amount'], 'USD')
            else:
                owing_amount = 0
            # validate if client is permanent
            if cl.station_number is None:
                return JsonResponse({'warning': 'Please update the client to be a permanent member'})
            else:
                monthly_obj = models.Transaction(
                    user=request.user,
                    client=cl,
                    product=p,
                    status='monthly',
                    work_station=WorkStation.objects.get(id=cl.station_number.id),
                    amount=request.POST['amount'],
                    owing=owing_amount
                )
                monthly_obj.save()
                return JsonResponse({
                    'success': 'transaction successfully created'
                })
        else:
            # day desk transaction
            day_obj = models.Transaction(
                user=request.user,
                client=cl,
                product=p,
                status='day',
                amount=request.POST['amount'],
                work_station=WorkStation.objects.get(id=request.POST['station'])
            )
            day_obj.save()
            print('saved')
            return JsonResponse({
                'success': 'transaction successfully created'
            })
    return JsonResponse({
        'failed': 'transaction failed successfully'
    })


@login_required(login_url="/accounts/login")
def Account(request, pk):
    q = request.GET.get('q') if request.GET.get('q') is not None else ''
    client = get_object_or_404(Client, id=pk)
    trans = models.Transaction.objects.filter(client=client)
    acc_transactions = trans.filter(
        Q(date_created__icontains=q) |
        Q(amount__icontains=q) |
        Q(owing__icontains=q)
    )
    return render(
        request,
        'transactions/account.html',
        {
            'transactions': acc_transactions or trans,
            'client': client
        }
    )

# function for total amount of expenses computation
# worried with performance as the dataset increases :(
def salesTotal(sales_data):
    total_sales = 0
    exp = sales_data.annotate(total=Sum('amount'))
    for exp in exp:
        total_sales = exp.amount + total_sales
    return total_sales

# account pdf generator
@login_required(login_url="/accounts/login")
def clientAccountPdfGenerator(request, pk):
    template_name = "reports/clientAccountPdf.html"
    client = get_object_or_404(Client, id=pk)
    client_transactions = models.Transaction.objects.filter(client=client)

    return render_to_pdf(
        template_name,
        {
            "client": client,
            "transactions": client_transactions,
            'date': datetime.now()
        },
    )

# sales pdf generation
# daily report
@login_required(login_url="/accounts/login")
def dailyReport(request):
    template_name = 'reports/salesPdf.html'
    # query today's expenses data
    sales = models.Transaction.objects.filter(date_created=date.today())
    return render_to_pdf(
        template_name,
        {
            "sales": sales,
            'title': 'Today(s) Sales',
            'date': date.today(),
            'total': salesTotal(sales)
        },
    )


# monthly report
@login_required(login_url="/accounts/login")
def monthlyReport(request):
    # computation for this month data
    today = date.today()
    current_month = today.month
    print(current_month)
    template_name = 'reports/salesPdf.html'
    sales = models.Transaction.objects.filter(date_created__month=current_month)
    print(sales)
    return render_to_pdf(
        template_name,
        {
            "sales": sales,
            'title': 'Monthly Sales',
            'date': date.today(),
            'total': salesTotal(sales)
        },
    )

linspot_business_management_system/templates/transactions/account.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}{{client.name}} | account{% endblock title %}
{% block content %}
<div class="pos">
    <div>
        <div class="title d-flex justify-content-end align-items-center" style="opacity: 1 !important;">
            <h4 class="w-100">Account for {{client.name}}
                <span class="px-1">
                    <i class='bx bxs-circle'></i>
                    {{client.member_status|title}}
                </span>
            </h4>
            <div class="d-flex align-items-center justify-content-end w-100">
                <span class="py-2 shadow px-2">
                    <a href='{% url 'transactions:clientAccount' client.id %}' class="btn btn-secondary btn-sm" type="button">
                        Download Pdf
                        <span class='px-1'><i class='bx bx-download' ></i></span>
                    </a>
                </span> 
                <span class="py-2 shadow px-2">
                    <form method="get" class="d-flex align-items-center">
                        <input type="search" name="q" class="form-control shadow" placeholder="transaction">
                    </form>
                </span>   
            </div> 
        </div>
        <div class="row mt-3">
            <div class="col-12">
                <div class='personal-info border p-2'>
                    <span>
                        <i class='bx bx-buildings' ></i>
                        {{client.address}}
                    </span>
                    <span class='px-2'>|</span>
                    <span>
                        <i class='bx bx-phone' ></i>
                        {{client.phonenumber}}
                    </span>
                    <span class='px-2'>|</span>
                    <span>
                        Id Number: {{client.id_number}}
                    </span>
                    <span class='px-2'>|</span>
                    <span>Station Number: {{client.station_number.station}}</span>
                </div>
                <div class="Day-Desks mt-3">
                    <h6>Account transactions</h6>
                    <table class='todays-vouchers list-unstyled p-2 table-primary table table-striped mt-4 table-responsive'>
                        <thead>
                            <th>Date</th>
                            <th>Details</th>
                            <th>Amount</th>
                            <th>Owing</th>
                        </thead>
                        <tbody>
                            {% for transaction in transactions %}
                            <tr>
                                <td>{{transaction.date_created}}</td>
                                <td>{{transaction.product}}</td>
                                <td>{{transaction.amount}}</td>
                                {% if transaction.owing == 0 %}
                                    <td>-----</td>
                                {% else %}
                                    <td>{{transaction.owing}}</td>
                                {% endif %}
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div> 
        </div>
    </div>
</div>
{% endblock content %}

linspot_business_management_system/templates/transactions/transaction_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Create Book</title>
    {{ form.media.css }}
    <style>
        input, select {width: 100%}
    </style>
</head>
<body>
    <h1>Create a new Book</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit">
    </form>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    {{ form.media.js }}
</body>
</html>

linspot_business_management_system/templates/transactions/transactions.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Transactions{% endblock title %}
{% block content %}
<div class="pos">
    <div>
        <div class="title d-flex justify-content-end align-items-center" style="opacity: 1 !important;">
            <h4 class="w-100">
                <span class="px-1">
                    <i class='bx bxs-circle'></i>
                    Sales Transactions
                </span>
            </h4>
            <div class="d-flex align-items-center justify-content-end w-100">
                <span class="py-2 shadow px-2">
                    <form method="get" class="d-flex align-items-center">
                        <input type="search" name="q" class="form-control shadow" placeholder="transaction">
                    </form>
                </span>
            </div>
        </div>
        <div class="row mt-3">
            <div class="col-10">
                <div class="mt-3">
                    <h6>Total USD${{total}}.00</h6>
                    <table class='todays-vouchers list-unstyled p-2 table-primary table table-striped mt-4 table-responsive'>
                        <thead>
                            <th>Date</th>
                            <th>Details</th>
                            <th>Amount</th>
                            <th>Note</th>
                        </thead>
                        <tbody>
                            {% for transaction in transactions %}
                            <tr>
                                <td>{{transaction.date_created}}</td>
                                <td>{{transaction.client}}</td>
                                <td>{{transaction.amount}}</td>
                                <td>{{transaction.note}}</td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
                  <div class="col-2">
            <div class="container mt-5">
                <div class="report-btns">
                    <div class="mt-2 mb-2">
                        <a href="{% url 'transactions:dailyReport' %}" class="btn btn-primary text-light w-100">Daily report</a>
                    </div>
                    <div class="mt-2">
                        <a href="{% url 'transactions:monthlyReport' %}" class="btn btn-primary text-light w-100">Monthly report</a>
                    </div>
                    <div class="mt-2 mb-2">
                        <button class="btn btn-primary text-light w-100 custom">Custom report</button>
                    </div>
                </div>
                <div class="custom-form mt-2 hidden">
                    <div class="back w-100 py-2 px-2">
                        <i class='bx bxs-left-arrow' style="color: #F99417;"></i>
                        <small>back</small>
                        <hr style="border: 1px solid #333 !important;">
                    </div>
                    <p class="mt-3">Choose dates</p>
                    <form method="get" id='custom_form'>

                        <input type="text" name="q" value="custom" hidden>
                        <div>
                            <label for="id_from">From</label>
                            <input type="date" name="from" id="id_from" class="form-control">
                        </div>
                        <div>
                            <label for="id_from">To</label>
                            <input type="date" name="to" id="id_to" class="form-control">
                        </div>
                        <div class="d-flex justify-content-end mt-3">
                            <button class="btn btn-secondary" type="submit" >submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        </div>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', (event) => {
        const expenses = document.querySelector('.expenses');
        const overlay = document.querySelector(".overlay");
        const expensesModal = document.querySelector('.expenses-modal');
        const closeModalBtn = document.querySelectorAll(".close");

        //custom report
        const reportBtn = document.querySelector('.custom');
        const backBtn = document.querySelector('.back');


        expenses.addEventListener(
            'click', ()=>{
                expensesModal.classList.remove("hidden");
                overlay.classList.remove("hidden");
            }
        )

        closeModalBtn.forEach((btn)=>{
            btn.addEventListener(
                'click', ()=>{
                    expensesModal.classList.add("hidden");
                    overlay.classList.add("hidden");
                }
            )
        })

        reportBtn.addEventListener(
            'click', ()=>{
                document.querySelector('.custom-form').classList.remove('hidden');
                document.querySelector('.report-btns').classList.add('hidden');
            }
        )

        backBtn.addEventListener(
            'click', ()=>{
                document.querySelector('.custom-form').classList.add('hidden');
                document.querySelector('.report-btns').classList.remove('hidden');
            }
        )

        $('#custom_form').submit(function(e) {
            e.preventDefault();
            const data = {
                date_from: $('#id_from').val(),
                date_to: $('#id_to').val(),
            }
            console.log(data)
            $.ajax({
                url: '{% url 'expenses:customReport'%}',
                type: 'GET',
                data: data,
                }).done(function(response) {

            })
        })

    })
</script>
{% endblock content %}