client/urls.py
from . import views
from django.urls import path
from django.views.generic import TemplateView

app_name = "client"
urlpatterns = [
    path("", views.ClientsListView, name="clients"),
    path("clientDetail/<int:pk>", views.ClientsDetailView, name="detail"),
    path("createClient/", views.ClientCreateView, name="createClient"),
    path("createPermanent/", views.PermanentCreateView, name='createPermanent'),
    path(
        "clientCancellatioin/<int:pk>",
        views.ClientCancellation,
        name="clientCancellation",
    ),
    
    path("updatePermanent/<int:pk>", views.UpdateNonPermenent, name='updatePermanent'),
    path("updateNonPermanent/<int:pk>", views.UpdateNonPermenent, name='updateNonPermanent'),
    
    # pdf 
    path("clientsPdf/", views.clientPdfGenerator, name="clientsPdf"),
    
    # Pos url
    path("pos/", views.Pos, name="pos"),
    path('posData/', views.posData, name='posData'),
]

linspot_business_management_system/users/urls.py
from django.urls import path

from linspot_business_management_system.users.views import (
    user_detail_view,
    user_redirect_view,
    user_update_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

transactions/urls.py
from django.urls import path
from . import views

app_name = 'transactions'
urlpatterns = [
    path("create/", views.TransactioinCreateView, name="create"),
    path('account/<int:pk>', views.Account, name='account'),
    path('pdf/<int:pk>', views.clientAccountPdfGenerator, name='clientAccount'),
    path('transactions/', views.transactions, name='transactions'),
    path('dailyReport/', views.dailyReport,  name='dailyReport'),
    # path('customReport/', views.customReport,  name='customReport'),
    path('monthlyReport/', views.monthlyReport,  name='monthlyReport'),
]

client/models.py
from django.db import models

# from phonenumber_field.modelfields import PhoneNumberField

member_status = (("non permanent", "non permanent"), ("permanent", "Permanent"))
station_status = (('occupied', 'occupied'), ('vaccant', 'vaccant'))

class WorkStation(models.Model):
    station = models.CharField(max_length=4)
    type = models.CharField(max_length=10)
    status = models.CharField(max_length=50, choices=station_status)

    def __str__(self) -> str:
        return f'{self.station} ({self.status})'
    
class Client(models.Model):
    name = models.CharField(max_length=50)
    phonenumber = models.CharField(max_length=50)
    address = models.CharField(max_length=50, null=True, blank=True)
    id_number = models.CharField(max_length=50, null=True, blank=True)
    station_number = models.OneToOneField(WorkStation, on_delete=models.CASCADE, null=True, blank=True)
    member_status = models.CharField(choices=member_status, max_length=50)
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)
    count = models.IntegerField(null=True, blank=True, default=0)

    def __str__(self):
        return self.name


class Cancellation(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    user = models.ForeignKey("users.User", on_delete=models.CASCADE)
    note = models.TextField()

    def __str__(self):
        return self.client.name


class Account(models.Model):
    client = models.ForeignKey(Client, on_delete=models.CASCADE)
    transaction = models.ForeignKey(
        "transactions.Transaction", on_delete=models.CASCADE
    )
    status = models.CharField(max_length=50)

    def __str__(self):
        return f"{self.client.name} ({self.status})"


    

linspot_business_management_system/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for Linspot business management system.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    # First and last name do not cover name patterns around the globe
    name = CharField(_("Name of User"), blank=True, max_length=255)
    first_name = None  # type: ignore
    last_name = None  # type: ignore

    def get_absolute_url(self) -> str:
        """Get URL for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

client/forms.py
from django.forms import ModelForm
from client.models import Client, Cancellation

    
class ClientForm(ModelForm):
    
    class Meta:
        model = Client
        exclude = ("user", "count")

class ClientMememberForm(ModelForm):
    class Meta:
        model = Client
        exclude = ("user", "count")


class ClientDayForm(ModelForm):
    class Meta:
        model = Client
        exclude = ("user", "count", "id_number", "address")


class ClientCancellation(ModelForm):
    class Meta:
        model = Cancellation
        exclude = ("user",)

linspot_business_management_system/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User
        error_messages = {
            "username": {"unique": _("This username has already been taken.")},
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """

client/views.py
import datetime
from client.forms import *
from django.db.models import Q
from django.utils import timezone
from django.contrib import messages
from django.shortcuts import render
from django.http import JsonResponse
from transactions.models import Transaction
from vouchers.models import voucherTransaction
from transactions.forms import TransactionForm
from client.models import Client, Account, WorkStation
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404


# pdf
from config.utils import render_to_pdf


@login_required(login_url="/accounts/login")
def ClientsListView(request):
    q = request.GET.get("q") if request.GET.get("q") != None else ""

    clients = Client.objects.filter(Q(member_status=q) | Q(name__icontains=q))

    return render(
        request,
        "clients/client_list.html",
        {"clients": clients or Client.objects.all()},
    )


@login_required(login_url="/accounts/login")
def ClientsDetailView(request, pk):
    cl = get_object_or_404(Client=pk)
    transactions = Account.objects.filter(client=cl)
    return render(
        request,
        "clients/client_detail.html",
        {"client": cl, "transactions": transactions},
    )

# non permanent client
@login_required(login_url="/accounts/login")
def ClientCreateView(request):
    if request.method == "POST":
        # Validation for client existance
        if Client.objects.filter(phonenumber=request.POST["phonenumber"]).exists():
            return JsonResponse({
                'warning':'Client already exists'
            })
        client = Client(
            user = request.user,
            name = request.POST['name'],
            phonenumber = request.POST['phonenumber'],
            member_status = 'non permanent'
        )
        client.save()
        return JsonResponse({
            'success':'Client created successfully'
        })
    return JsonResponse({
        'error':'failed creating a client'
    })

# permanent client
@login_required(login_url="/accounts/login")
def PermanentCreateView(request):
    if request.method == "POST":
        station = get_object_or_404(WorkStation, id = request.POST['station'])
        # Validation for client existance
        if Client.objects.filter(phonenumber=request.POST["phonenumber"]).exists():
            return JsonResponse({
                'warning':'Client already exists'
            })
        print(request.POST['station'])
        # create new permanent client object
        client = Client(
            user = request.user,
            name = request.POST['name'],
            phonenumber = request.POST['phonenumber'],
            address = request.POST['address'],
            id_number = request.POST['id_number'],
            station_number = station,
            member_status = 'permanent'
        )
        client.save()
        # update the workstation status
        station.status = 'occupied'
        station.save()
        return JsonResponse({
            'success':'Client created successfully'
        })
    return JsonResponse({
        'error':'failed creating a client'
    })

@login_required(login_url="/accounts/login")
def UpdatePermnent(request, pk):
    cl = get_object_or_404(Client, id=pk)
    form = ClientMememberForm(instance=cl or None)
    if request.POST['name'] == '' or request.POST['phonenumber'] == '':
        messages.warning(request, 'Please check name or phone field(s), cant be empty ')
        return redirect('client:clients')
    if form.is_valid():
        form.save()
        messages.success(request, f"client successfully updated")
        return redirect('client:clients')
    return render(
        request, "clients/createClient.html", {"form": form, "client": cl}
    )
        

@login_required(login_url="/accounts/login")
def UpdateNonPermenent(request, pk):
    cl = get_object_or_404(Client, id=pk)
    form = ClientDayForm(instance=cl or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, f"client successfully updated")    
            return redirect('client:clients')
        print('FAILED')
    return render(
        request, "clients/createClient.html", {"form": form, "client": cl}
    )

@login_required(login_url="/accounts/login")
def clientCancellatioin(request, pk):
    cl = get_object_or_404(Client=pk)
    return render(request, "client/cancleClient.html")

# renders the pos html
@login_required(login_url="/accounts/login")
def Pos(request):
    return render(
        request,
        "pos.html",
        {
            "clients": Client.objects.all(), "account": Account.objects.all(),
            'stations': WorkStation.objects.filter(status = 'vaccant'),
            'vouchers' : voucherTransaction.objects.all(),
            'desks' : Transaction.objects.filter(status = 'day'),
            'form':TransactionForm()
        },
    )
    

@login_required(login_url="/accounts/login")
def posData(request):
    clients = Client.objects.all()
    return JsonResponse({
        'clients': list(clients.values())
    })


@login_required(login_url="/accounts/login")
def clientPdfGenerator(request):
    template_name = "reports/clientsPdf.html"
    clients = Client.objects.all()
    return render_to_pdf(
        template_name,
        {
            "clients": clients,
            'date': datetime.date.today()
        },
    )
   
# provide data to django-select2  
@login_required(login_url="/accounts/login")
def clientData(request):
    clients = Client.objects.all()
    json_data = []
    for client in clients:
        json_data.append({"id": client.id, "text": client.name})

    return JsonResponse(json_data, safe=False)

linspot_business_management_system/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

linspot_business_management_system/templates/clients/client_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Clients{% endblock title %}
{% block content %}
<div class="client mt-3">
    <div class="title d-flex justify-content-between align-items-center">
        <h4>Clients</h4>
        <div class="d-flex align-items-center">
            <span class="py-2 shadow px-2">
                <form method="get">
                    <input type="text" name="q" hidden>
                    <button class="btn px-2">All Members</button>
                </form>
            </span>
            <span class="py-2 shadow px-2">
                <form method="get">
                    <input type="text" name="q" value="permanent" hidden>
                    <button class="btn  px-2">Permanent</button>
                </form>
            </span>
            <span class="py-2 shadow px-2">
                <form method="get">
                    <input type="text" name="q" value="non permanent" hidden>
                    <button class="btn  px-2">Non Permanent</button>
                </form>
            </span>
            <span class="py-2 shadow px-2">
                <a href="{% url 'client:clientsPdf' %}" class="btn btn btn-secondary">Download Pdf
                    <span class='px-1'><i class='bx bx-download' ></i></span>
                </a>
            </span>
            <span class="py-2 shadow px-2">
                <form method="get" class="d-flex align-items-center">
                    <input type="search" name="q" class="form-control shadow" placeholder="search member">
                </form>
            </span>
        </div>
    </div>
    <div class="row mt-3">
        <table class="table table-striped table-responsive">
            <thead>
                <th>Name</th>
                <th>Contact Details</th>
                <th>Station Number</th>
                <th>Membership</th>
                <th>Actions</th>
            </thead>
            <tbody>
                {% for client in clients %}
                    <tr>
                        <td>{{client.name|title}}</td>
                        <td>{{client.phonenumber}}</td>
                        <td>{{client.station_number.station}}</td>
                        <td>{{client.member_status}}</td>
                        <td>
                            {% if client.member_status == 'permanent' %}
                                <span>
                                    <a href="{% url 'client:updatePermanent' client.id %}">
                                        <i class='bx bx-edit' style="color: #664147 !important; font-size:18px"></i>
                                    </a>
                                </span>
                                <span class="px-2" style="color: #476641 !important; font-size:18px">|</span>
                                <span class="">
                                    <a href="{% url 'transactions:account' client.id %}">
                                        <i class='bx bxs-user-account' style="color: #664147 !important; font-size:18px"></i>
                                    </a>
                                </span>
                            {% else %}
                                <span>
                                    <a href="{% url 'client:updateNonPermanent' client.id %}">
                                        <i class='bx bx-edit' style="color: #664147 !important; font-size:18px"></i>
                                    </a>
                                </span>
                                <span class="px-2" style="color: #476641 !important; font-size:18px">|</span>
                                <span class="">
                                    <a href="{% url 'transactions:account' client.id %}">
                                        <i class='bx bxs-user-account' style="color: #664147 !important; font-size:18px"></i>
                                    </a>
                                </span>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock content %}

linspot_business_management_system/templates/clients/createClient.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="create-client">
    <h3 class="py-4">Update details for {{client.name|title}}</h3>
    <form method="post">
        {% csrf_token %}
        {{form|crispy}}
        <button class="btn btn-primary btn-sm w-100">Save changes</button>
    </form>
</div>
{% endblock content %}